### ISSUE TITLE
Trouble detecting MetaMask

### ISSUE THREAD

**Issue by jzstern** [bmiller59/vue-cli-plugin-ethers#1]
Learning ethers.js and stumbled across your library - this is awesome!

Love how you have everything setup, although I'm not able to properly detect the web3 injection from MetaMask (or if MetaMask is installed). I've been tweaking your module but `window.ethereum` appears to be undefined in `ethersConnect.js` and I'm not sure how else to check if the client has MetaMask.

Would love to use your package in a project but I think it might be a bit out of date. Do you happen to know if it's compatible with ethers 5.0.8? If not, any plans to update it?

No worries if not - thanks for open sourcing this 😄

**Comment by bmiller59** [comment]
@jzstern I am looking into this. I haven't updated this plugin for about 2 years and it is likely things have changed with metamask, etc. in that time. ;) I hope to have time to update and will let you know.

**Comment by jzstern** [comment]
Right on - appreciate it!

**Comment by bmiller59** [comment]
@jzstern Hi! I have updated this plugin to use the latest ethers 5.0.8 and to be compatible with the latest EIP-1193 compatible version of `window.ethereum` provided by MetaMask, etc. I have tested it and it all seems to be working as expected. 

To try it out, make sure you have discarded/stashed the changes in your project related to the older version of this plugin, or are on a fresh vue project. Then run `vue add ethers` and log into MetaMask and you should be good to go! Let me know if you encounter other issues with it.
